name:  pipelines3
on:
  workflow_dispatch:

permissions:
 id-token: write
 contents: write
 # This is required for actions/checkout@v2

jobs:
  copytoawss3bucket:
    runs-on: ubuntu-latest
    steps:
    - name: configureawscredentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       role-to-assume: arn:aws:iam::719814415405:role/github
       role-session-name: samplerolesession
       aws-region: ap-south-1
    - name: Checkout
      uses: actions/checkout@v2
    - name: copying files to s3 bucket
      run: aws s3 cp ./source s3://136912151821/ --recursive



